apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hcloud-csi
  namespace: flux-system
spec:
  interval: 30m
  releaseName: hcloud-csi
  chart:
    spec:
      chart: hcloud-csi
      version: 2.13.0
      targetNamespace: kube-system
      sourceRef:
        kind: HelmRepository
        name: hetzner
        namespace: flux-system
  