apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hcloud-csi
  namespace: flux-system
spec:
  interval: 30m
  releaseName: hcloud-csi
  targetNamespace: kube-system
  chart:
    spec:
      chart: hcloud-csi
      version: 2.13.0
      sourceRef:
        kind: HelmRepository
        name: hcloud
        namespace: flux-system
  values:
    node:
      kubeletDir: /var/lib/k0s/kubelet
  