apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hcloud-cloud-controller-manager
  namespace: flux-system
spec:
  interval: 30m
  releaseName: hcloud-cloud-controller-manager
  targetNamespace: kube-system
  chart:
    spec:
      chart: hcloud-cloud-controller-manager
      version: 1.23.0
      sourceRef:
        kind: HelmRepository
        name: hcloud
        namespace: flux-system
  values:
    config:
      privateNetworks: 
        enabled: true
        id: spoletum-dev
        subnet: 10.0.0.0/24