apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hcloud-csi
  namespace: flux-system
spec:
  interval: 30m
  releaseName: hcloud-csi
  targetNamespace: kube-system
  chart:
    spec:
      chart: hcloud-csi
      version: 2.13.0
      sourceRef:
        kind: HelmRepository
        name: hcloud
        namespace: flux-system
  values:
    node:
      kubeletDir: /var/lib/k0s/kubelet
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hcloud-ccm
  namespace: flux-system
spec:
  interval: 30m
  releaseName: hcloud-ccm
  targetNamespace: kube-system
  chart:
    spec:
      chart: hcloud-cloud-controller-manager
      version: 1.23.0
      sourceRef:
        kind: HelmRepository
        name: hcloud
        namespace: flux-system
  values:
    env:
      # See line 29 of https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/chart/values.yaml
      HCLOUD_NETWORK:
        value: spoletumnet-nonprod
