apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: flux-system
spec:
  interval: 30m
  releaseName: opentelemetry-collector
  targetNamespace: open-telemetry
  install:
    createNamespace: true
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.122.5"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  values:
    mode: dameonset