apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dapr
  namespace: flux-system
spec:
  interval: 30m
  releaseName: dapr
  targetNamespace: dapr-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: dapr
      version: 1.15.4
      sourceRef:
        kind: HelmRepository
        name: dapr
        namespace: flux-system
  values:
    global:
      ha:
        replicaCount: 1
