apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arangodb
  namespace: flux-system
spec:
  interval: 30m
  releaseName: arangodb
  targetNamespace: arangodb
  chart:
    spec:
      chart: arangodb
      version: 4.2.47
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    cluster:
      enabled: false
    etcd:
      replicaCount: 1
    pulsar:
      enabled: false
    minio:
      mode: standalone
