apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 30m
  releaseName: traefik
  targetNamespace: traefik
  install:
    createNamespace: true
  chart:
    spec:
      chart: traefik
      version: 35.0.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    service:
      annotations:
        load-balancer.hetzner.cloud/network-zone: eu-central