apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 30m
  releaseName: traefik
  targetNamespace: traefik
  install:
    createNamespace: true
  chart:
    spec:
      chart: traefik
      version: 35.0.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    deployment:
      initContainers:
        # Ugly hack as explained in the values.yaml template.
        - name: init-letsencrypt
          image: busybox:latest
          command: ["sh", "-c", "mkdir -p /data; touch /data/acme.json; chmod -v 600 /data/acme.json"]
          volumeMounts:
            - name: data
              mountPath: /data
    service:
      annotations:
        load-balancer.hetzner.cloud/network-zone: eu-central
    certificatesResolvers:
      letsencrypt:
        acme:
          email: spoletum@spoletum.com
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web
    persistence:
      enabled: true