apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 30m
  releaseName: traefik
  targetNamespace: traefik
  install:
    createNamespace: true
  chart:
    spec:
      chart: traefik
      version: 35.0.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    deployment:
      initContainers:
        - name: volume-permissions
          image: busybox:latest
          command: ["sh", "-c", "ls -la /; touch /data/acme.json; chmod -v 600 /data/acme.json"]
          volumeMounts:
          - mountPath: /data
            name: data
    podSecurityContext:
      fsGroup: 65532
      fsGroupChangePolicy: "OnRootMismatch"
    service:
      annotations:
        load-balancer.hetzner.cloud/network-zone: eu-central
    certificatesResolvers:
      letsencrypt:
        acme:
          email: spoletum@spoletum.com
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web
    persistence:
      enabled: true