apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: milvus
  namespace: flux-system
spec:
  interval: 30m
  releaseName: milvus
  targetNamespace: milvus
  chart:
    spec:
      chart: milvus
      version: 4.2.47
      sourceRef:
        kind: HelmRepository
        name: milvus
        namespace: flux-system
  values:
    cluster:
      enabled: false
    etcd:
      replicaCount: 1
    pulsar:
      enabled: false
    minio:
      mode: standalone
