apiVersion: v1
kind: Secret
metadata:
    name: hetzner
    namespace: kube-system
type: Opaque
data:
    token: ENC[AES256_GCM,data:98MB/AU91H+rdDryYX46K4CXDl2SasLcu2sG8fZ5hsAQzeGAoGEhshjkZ7LvlTX1gAQvmmNWd4GbBnPPWO1GanGLCxsr4nfRUVyBIkVrM7QCy4Byf/2RPg==,iv:KGdRZmbSYIsIAo2F25vTGzGRR0cwKcjSvin1HJm4NI8=,tag://8d4yzUdNYmlU/CVS2Peg==,type:str]
sops:
    age:
        - recipient: age1hnqczxtcgk93gnlng7t58rah58tszdwz5ql0hjs7mcc5fr3lhpmqwwlkre
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS29XSFp6a2x6SENVcGtY
            VkhBQktQUEVEdVg5N1RaejhXdkZNTjFEZ2xrCnhUZ001cFlpK1V4NzRqa3RRTHRS
            K0tLZkhsK3RtcVl6MzZHY21RSVQyRWMKLS0tIHNJVktSVmxUOWZZUHZNUnV6akYx
            eWpLb2s0WmoycldkVDZzUTlmUk1naGMKTV5EolE5XJYSkcZmdGtP3lbioXYuqGoE
            bgLUH84FXKiKGtNpvOQO5ac6aeDthNFFmjCM/Hhjk2CD1f7EIA3vOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-19T12:43:56Z"
    mac: ENC[AES256_GCM,data:kDFifbFiC6qbsYkQ973pkU654V7WiqS5yAR4Pozfw1RI5r9cZ+2ILoPfEkq33hF9hElTbPWYtDCzMw/uMc88qi9mRdNYIwWEM/aZP46GVT5kQ3v1sjbFpZrzl8ef1RczBk3v0trjjkjc297w+Pk96F0LMFoI3NqtYJX17zUHrF4=,iv:AOqCW5bcW2bOdmdIxXZQTErP+IJms83T4E5JmrHZWKg=,tag:mD7ftDn1n+fRRexUoafUfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2