apiVersion: v1
kind: Secret
metadata:
    name: hcloud
    namespace: kube-system
type: Opaque
data:
    token: ENC[AES256_GCM,data:enSKQiJJjhuElZ/+ZpMl5UdQWBBTOi1iHf4XaRFFdHapHwx3juc/AJONgo/3xMNnov+aeo+yZgvQEt+sLnAQMol0MDQ7jY8pTA+p99Joz3roW7pxUme9Dw==,iv:r37l7NeF+M4BKkuoKlQq2TO0c9zp3iwBIoLRzHhaMBc=,tag:km4QhLkrMdLB8IPAk1Hs9w==,type:str]
sops:
    age:
        - recipient: age1hnqczxtcgk93gnlng7t58rah58tszdwz5ql0hjs7mcc5fr3lhpmqwwlkre
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS29XSFp6a2x6SENVcGtY
            VkhBQktQUEVEdVg5N1RaejhXdkZNTjFEZ2xrCnhUZ001cFlpK1V4NzRqa3RRTHRS
            K0tLZkhsK3RtcVl6MzZHY21RSVQyRWMKLS0tIHNJVktSVmxUOWZZUHZNUnV6akYx
            eWpLb2s0WmoycldkVDZzUTlmUk1naGMKTV5EolE5XJYSkcZmdGtP3lbioXYuqGoE
            bgLUH84FXKiKGtNpvOQO5ac6aeDthNFFmjCM/Hhjk2CD1f7EIA3vOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-19T16:20:39Z"
    mac: ENC[AES256_GCM,data:0pUE5OE3WwQ7bTSXkf/T3oeDzDBfoOxlrjQ/RR5U3IDj6ridutwPwXBgwUtKc0/Jf34SB+I7lzKcH9KQieWUJZK8EjumVReVfXDQWORdwJlVVSwiMjKmr9UU3Cl6x75n6PGzpgvY0QDwOaqMUZoxrsPZ83tRztF5aZiP1smoBms=,iv:SqZN8Ib61eOC1PFEy1wdwNJcFgz+dclX4sDb4jyn9Mc=,tag:Gh92xBWIyeSqpKuDgk+YDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
