apiVersion: v1
kind: Secret
metadata:
    name: hcloud
    namespace: kube-system
type: Opaque
data:
    token: ENC[AES256_GCM,data:98MB/AU91H+rdDryYX46K4CXDl2SasLcu2sG8fZ5hsAQzeGAoGEhshjkZ7LvlTX1gAQvmmNWd4GbBnPPWO1GanGLCxsr4nfRUVyBIkVrM7QCy4Byf/2RPg==,iv:KGdRZmbSYIsIAo2F25vTGzGRR0cwKcjSvin1HJm4NI8=,tag://8d4yzUdNYmlU/CVS2Peg==,type:str]
sops:
    age:
        - recipient: age1hnqczxtcgk93gnlng7t58rah58tszdwz5ql0hjs7mcc5fr3lhpmqwwlkre
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS29XSFp6a2x6SENVcGtY
            VkhBQktQUEVEdVg5N1RaejhXdkZNTjFEZ2xrCnhUZ001cFlpK1V4NzRqa3RRTHRS
            K0tLZkhsK3RtcVl6MzZHY21RSVQyRWMKLS0tIHNJVktSVmxUOWZZUHZNUnV6akYx
            eWpLb2s0WmoycldkVDZzUTlmUk1naGMKTV5EolE5XJYSkcZmdGtP3lbioXYuqGoE
            bgLUH84FXKiKGtNpvOQO5ac6aeDthNFFmjCM/Hhjk2CD1f7EIA3vOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-19T14:57:04Z"
    mac: ENC[AES256_GCM,data:ayP/zbbpwD0aJPkOLCYUv+vL2jh+MxnDeQJtjadLabYZ/Wc7w5GKTHoNM5+SU84XtRi07NJGCSEHQcimN0msjp8mMkPCnVP8OLyzyO/zmbw4FwKNze2FLGavWSD8w/KHW4bSw+X6ruoQzn+Y+6m5zdr2VOq8pMNtOFx2qdQEdWo=,iv:t5tfznOdqkEu8KWmCpP8n3mhKu+6S1spvsezjENH2EU=,tag:L+mKvdtx5ScPWPLJEn9qOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
