apiVersion: v1
kind: Secret
metadata:
    name: hcloud
    namespace: kube-system
type: Opaque
data:
    token: ENC[AES256_GCM,data:P7+Upof3YJ0KZSpjTSOnWD+EUzHQElocPkPJATAmp2puW3EWd+4NNDmZFNWl6BW0T6HAve8gwPbXM1Hy9WAceg==,iv:7zm8XrtUuxQJoQMPqZqFeBVwsT8VCyiesPoEPDxFdG8=,tag:G/JMLYVcOUIdmR+5XDwLKg==,type:str]
sops:
    age:
        - recipient: age1hnqczxtcgk93gnlng7t58rah58tszdwz5ql0hjs7mcc5fr3lhpmqwwlkre
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS29XSFp6a2x6SENVcGtY
            VkhBQktQUEVEdVg5N1RaejhXdkZNTjFEZ2xrCnhUZ001cFlpK1V4NzRqa3RRTHRS
            K0tLZkhsK3RtcVl6MzZHY21RSVQyRWMKLS0tIHNJVktSVmxUOWZZUHZNUnV6akYx
            eWpLb2s0WmoycldkVDZzUTlmUk1naGMKTV5EolE5XJYSkcZmdGtP3lbioXYuqGoE
            bgLUH84FXKiKGtNpvOQO5ac6aeDthNFFmjCM/Hhjk2CD1f7EIA3vOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-19T16:07:08Z"
    mac: ENC[AES256_GCM,data:V+9y9FQdQ3Dt1GIX0cyLGVOiIAXRvyBItdCpgorxq3q3uX2aDZf4zTEhN1fY+B1AfVZjFFN2Dko93zz1RCj8vppXYYVvcj4WhMYa2Cfp/unsyT0qhrRu5KP5qUKV0r/Tx6GsWZ2FBxo5nk3bTvd0Q+fMavpngG/pxxlk2t5SfGg=,iv:a12Z4HMrEGLOBpu5VD/XfTsgd7DpkZMLpVQKNRriNfg=,tag:8UYuAx6HOjDTw8Z1BZuNvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
