apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  interval: 30m
  releaseName: tempo
  targetNamespace: grafana
  install:
    createNamespace: true
  chart:
    spec:
      chart: tempo
      version: "1.21.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    service:
      type: LoadBalancer